### PR TITLE
Change timer WantedBy to timers.target

### PR DESCRIPTION
**Pull request by jcrd**

### CODE REVIEW

**Comment by falconindy** [comment]
But why?

**Comment by jcrd** [comment]
From systemd.special(7) about timers.target:

> It is recommended that timer units installed by applications get pulled in via Wants=
   dependencies from this unit. This is best configured via WantedBy=timers.target in the timer
   unit's "[Install]" section.

**Comment by falconindy** [comment]
Okay, but do you have any *real* motivation for this beyond what the doc says? Making this has consequences -- pkgfile updating will block normal bootup. I don't consider that reasonable.

**Comment by jcrd** [comment]
That's a good point. multi-user.target makes sense in this case.

**Comment by abouvier** [comment]
> Okay, but do you have any _real_ motivation for this beyond what the doc says? Making this has consequences -- pkgfile updating will block normal bootup. I don't consider that reasonable.

I don't understand your argument. To begin with, every timer on my system use WantedBy=timers.target, even the greedy ones. And to delay the service activation when booting up (even with Persistent=yes) you can use RandomizedDelaySec. This is how fstrim.timer is configured for example.

> Persistent=
> Takes a boolean argument. If true, the time when the service unit was last triggered is stored on disk. When the timer is activated, the service unit is triggered immediately if it would have been triggered at least once during the time when the timer was inactive. **Such triggering is nonetheless subject to the delay imposed by RandomizedDelaySec=.** This is useful to catch up on missed runs of the service when the system was powered down.

**Pull request closed without merging**
